# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm6115-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter caprip,$(TARGET_DEVICE)),)

endif
